#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug 29 16:41:06 2025

@author: mlampert
"""

#Core modules
import os
import copy
import time as time_mod
import pickle
import warnings
warnings.filterwarnings("ignore")

import flap
import flap_nstx
flap_nstx.register('NSTX_GPI')

from flap_nstx.gpi import analyze_gpi_structures, transform_frames_to_structures, read_analyzed_keys
from flap_nstx.thomson import get_fit_nstx_thomson_profiles

import flap_mdsplus

flap_mdsplus.register('NSTX_MDSPlus')

thisdir = os.path.dirname(os.path.realpath(flap_nstx.__file__))
fn = os.path.join(thisdir,"flap_nstx.cfg")
flap.config.read(file_name=fn)

#Scientific modules
from matplotlib.backends.backend_pdf import PdfPages

import numpy as np
import pandas

#Plot settings for publications
wd=flap.config.get_all_section('Module NSTX_GPI')['Working directory']
fig_dir='/plots'


def read_all_blob_data(time_range_around_peak=5e-3, #Reads either mean or full blob results. the original read_blob_data procedure reads one shot only
                       nocalc=False,
                       recalc_tracking=False,
                       
                       min_structure_lifetime=20,
                       str_finding_method='watershed',
                       fix_angle_for_correlation=False,
                       read_mean_results=False, #Obsolete
                       averaging='shot',
                       average='avg', #[avg, std, max, no] returns average, returns standard deviation, returns maximum value in the shot (for read_mean_results), or for the blob (average_blob_by_blob)
                       
                       replicate_histogram2=False,
                       replicate_old_read_blob_data=False,
                       
                       read_l_mode_only=False,
                       read_h_mode_only=False,
                       filtered_blob_db=False,
                       ):
    
    
    """
    Reads, processes, and aggregates structure tracking data across multiple experimental shots.

    (Generated by Gemini

    This function iterates through a database of experimental shots (either the full 
    database or filtered by L-mode/H-mode). For each shot, it reads the tracking data, 
    calculates static and differential physical properties of the identified structures 
    (blobs), and aggregates the results. The aggregation can be done on a shot-by-shot 
    basis, blob-by-blob basis, or omitted entirely for raw data. The final processed 
    dictionary is cached as a `.pickle` file to speed up subsequent runs.

    Args:
        time_range_around_peak (float or list, optional): The time window to process 
            around a peak event. 
            - If a float: The range is `[t_peak - time_range, t_peak + time_range]`.
            - If a list: The range is `[t_peak - time_range[0], t_peak + time_range[1]]`.
            Defaults to 5e-3.
        nocalc (bool, optional): If True, attempts to skip the calculation and directly 
            load the aggregated results from a cached `.pickle` file. Defaults to False.
        recalc_tracking (bool, optional): If True, forces the recalculation of the 
            structure tracking algorithms rather than loading tracked data from cache. 
            Defaults to False.
        min_structure_lifetime (int, optional): Minimum required lifetime (in frames) 
            for a structure to be included in the analysis. Defaults to 20.
        str_finding_method (str, optional): The image segmentation algorithm used 
            for finding structures ('watershed' or 'contour'). Defaults to 'watershed'.
        fix_angle_for_correlation (bool, optional): If True, performs fringe jump 
            correction for structure angles. Defaults to False.
        read_mean_results (bool, optional): [OBSOLETE] Legacy flag to read mean results. 
            If True, overrides `averaging` to 'shot'. Defaults to False.
        averaging (str, optional): The aggregation methodology. Options are:
            - 'shot': Averages the properties of all blobs within a single shot.
            - 'blob': Retains averages on a blob-by-blob basis.
            - 'no': No averaging; raw time-series data is appended.
            Defaults to 'shot'.
        average (str, optional): The specific statistical function to apply when 
            aggregating data (e.g., 'avg' for mean, 'std' for standard deviation, 
            'max' for maximum value). Defaults to 'avg'.
        replicate_histogram2 (bool, optional): Legacy compatibility flag. Finite difference 
            calculations normally result in `N-1` data points. This flag replicates 
            the behavior of an older `_histogram2` method by dropping the first data 
            point (a 'pre' difference shift) rather than appending a duplicate point 
            at the end. Overrides `averaging` to 'no'. Defaults to False.
        replicate_old_read_blob_data (bool, optional): Legacy compatibility flag. 
            Replicates older behavior by duplicating and appending the final data 
            point to differential arrays to artificially maintain an array length 
            of `N`. Defaults to False.
        read_l_mode_only (bool, optional): If True, filters the database to only 
            process L-mode shots. Defaults to False.
        read_h_mode_only (bool, optional): If True, filters the database to only 
            process H-mode shots. Defaults to False.
        filtered_blob_db (bool, optional): If True, applies standard filtering 
            criteria when reading the L/H mode databases. Defaults to True.

    Raises:
        ValueError: If the `averaging` parameter is not one of: 'shot', 'blob', or 'no'.
        ValueError: If L/H mode reading is not enabled but `time_range_around_peak` 
            is provided as a list rather than a single numerical float.

    Returns:
        dict: A dictionary (`full_blob_db_data`) containing the aggregated structure 
            data across all processed shots. 
            - If `averaging` is 'shot': Keys map to 1D NumPy arrays of the aggregated 
              statistics (one value per shot).
            - If `averaging` is 'blob' or 'no': Keys map to lists of dictionaries, 
              where each dictionary contains the 'shot' ID and the respective 'data' 
              array for that shot/blob.
    """
    
    
    if read_mean_results:
        averaging='shot'
    
    pickle_filename=wd+'/processed_data/blob_database_shot_by_shot_blob_'+str_finding_method+'_'
    pickle_filename += averaging+'_avg__'+ average + '_calc__'
        
    if read_l_mode_only: pickle_filename += 'L_mode'
    if read_h_mode_only: pickle_filename += 'H_mode'
    
    pickle_filename += '.pickle'
    
    difference_method='pre', 
            
    if read_l_mode_only:
        blob_database=read_blob_lh_mode_database_file(l_mode=True,
                                                      filtered_blob_db=filtered_blob_db,
                                                      time_range_around_peak=time_range_around_peak)
    elif read_h_mode_only:
        blob_database=read_blob_lh_mode_database_file(h_mode=True,
                                                      filtered_blob_db=filtered_blob_db,
                                                      time_range_around_peak=time_range_around_peak)
    else:
        if not isinstance(time_range_around_peak,(int,float)):
            raise ValueError('time_range_around_peak needs to be a single number if l_mode or h_mode reading is not set.')
        blob_database=read_blob_database_file(time_range_around_peak=time_range_around_peak)
        
    analyzed_keys=read_analyzed_keys()
    
    diff_keys=['Velocity radial COG', 'Velocity poloidal COG',
               'Velocity radial centroid', 'Velocity poloidal centroid',
               'Velocity radial position', 'Velocity poloidal position',
               'Expansion fraction area', 'Expansion fraction axes',
               'Angular velocity angle', 'Angular velocity ALI'] #These are calculated at the time when the blob results are calculated
        
    additional_diff_keys=['Convexity', 'Solidity', 'Roundness', 'Total curvature',
                          'Total bending energy','Area','Elongation', 
                          'Size radial', 'Size poloidal'] # These are calculated in this method.

    ncalc=len(blob_database['shot'])

    full_blob_db_data={}

    for key in analyzed_keys:
        full_blob_db_data[key]=[]
    for key in additional_diff_keys:
        full_blob_db_data[key+' diff']=[]
    
    full_blob_db_error = copy.deepcopy(full_blob_db_data)

    curr_blob_data_ref = copy.deepcopy(full_blob_db_data)
    curr_blob_error_ref = copy.deepcopy(full_blob_db_data)

    if not os.path.exists(pickle_filename) or not nocalc:
        n_str = 0
        for ind in range(ncalc):
            start_time = time_mod.time()
            curr_shot_data = copy.deepcopy(curr_blob_data_ref)
            curr_shot_error = copy.deepcopy(curr_blob_error_ref)
            
            shot = blob_database['shot'][ind]
            if isinstance(blob_database['time'][ind],(list,np.ndarray)):
                time_range = blob_database['time'][ind]
                              
            else:
                time_range = [blob_database['time'][ind] - time_range_around_peak,
                              blob_database['time'][ind] + time_range_around_peak]
                
            # if type(blob_time)
            blob_results = read_blob_data(shot,
                                          time_range,
                                          nocalc = True,
                                          recalc_tracking = recalc_tracking,
                                          min_structure_lifetime = min_structure_lifetime,
                                          str_finding_method = str_finding_method,
                                          )
            if blob_results is None: continue
        
            flap.delete_data_object('*')
            str_by_str = transform_frames_to_structures(blob_results)
            if True:
            # try:
                for structure in str_by_str: 
                    for key in analyzed_keys + additional_diff_keys:
                        
                        if key in analyzed_keys:
                            if replicate_old_read_blob_data:
                                if key in diff_keys:
                                    str_key_data=np.append(structure[key], structure[key][-1])  #this is to match the same number of elements in the differential data
                                else:
                                    str_key_data=structure[key]
                            elif replicate_histogram2:
                                if key in diff_keys:
                                    str_key_data=structure[key]
                                else:
                                    str_key_data=structure[key][1:]
                            else:   #New scheme
                                pass
                            key_string_add=''
                            
                        elif key in additional_diff_keys:
                            str_key_data=[]
                            if difference_method == 'pre':
                                first_slice=slice(1,len(structure[key]))
                                second_slice=slice(0,len(structure[key])-1)
                                diff_multiplier=1
                                
                            elif difference_method == 'symmetric':                      #Implemented but unused. Would need to change the way the other diff keys are calculated.
                                first_slice=slice(2,len(structure[key]))
                                second_slice=slice(0,len(structure[key])-2)
                                diff_multiplier=0.5
                            
                            str_key_data=np.real(structure[key][first_slice] - 
                                                 structure[key][second_slice]) * diff_multiplier
                            if replicate_histogram2:
                                pass
                            elif replicate_old_read_blob_data:
                                str_key_data=np.append(str_key_data,str_key_data[-1])
                            else:   #New scheme
                                pass
                            
                            key_string_add=' diff'
                            
                        """
                        The idea with averaging is that if there is no averaging, just append the data to the previous.
                        If there is either shot or blob averaging, then append the blob average first no matter which
                        one is chosen. If shot average is chosen, then it's calculated as shot_averaged blob_averaged data
                        and not shot_averaged no_average data. They are different, but this way the result is not biased
                        towards long duraction structures but to the number of blobs which is more relevant.
                        """
                        str_key_data=np.asarray(str_key_data)
                        if averaging == 'no':
                            curr_shot_data[key + key_string_add]=np.append(curr_shot_data[key + key_string_add],
                                                                           str_key_data) 
                        elif averaging == 'shot' or averaging == 'blob':
                            str_key_data=str_key_data[~np.isnan(str_key_data)]
                            if averaging == 'shot':
                                curr_shot_error[key + key_string_add]=np.append(curr_shot_error[key + key_string_add],
                                                                                np.sqrt(np.var(str_key_data)))
                                
                            if average == 'avg':
                                curr_shot_data[key + key_string_add]=np.append(curr_shot_data[key + key_string_add],
                                                                               np.mean(str_key_data))
                            elif average == 'std':
                                curr_shot_data[key + key_string_add]=np.append(curr_shot_data[key + key_string_add],
                                                                               np.sqrt(np.var(str_key_data)))
                            elif average == 'max':
                                curr_shot_data[key + key_string_add]=np.append(curr_shot_data[key + key_string_add],
                                                                               np.max(str_key_data))
                                       
                for key in full_blob_db_data.keys():
                    if averaging == 'shot':
                        full_blob_db_data[key]=np.append(full_blob_db_data[key],
                                                      np.mean(curr_shot_data[key]))
        
                        full_blob_db_error[key]=np.append(full_blob_db_error[key],
                                                          np.mean(curr_shot_error[key]) /
                                                          np.sqrt(len(curr_shot_error[key])))
                    # else:
                    #     full_blob_db_data[key]=np.append(full_blob_db_data[key],
                    #                                      {'shot':shot,
                    #                                       'data':curr_shot_data[key]})
            # except Exception as e:
            #     print(f'Failed to gather data for shot {shot} due to {e}')
            remaining_time=(time_mod.time()-start_time)*(ncalc-ind-1)

            hours = int(remaining_time // 3600)
            minutes = int((remaining_time % 3600) // 60)
            seconds = int(remaining_time % 60)

            print('\rRemaining time from the calculation: '+f"{hours}h {minutes:02}min {seconds:02}sec", end="", flush=True)
        print(f'Total number of structures: {n_str}')
        
        pickle.dump(full_blob_db_data,open(pickle_filename,'wb'))
    else:
        full_blob_db_data=pickle.load(open(pickle_filename,'rb'))

    return full_blob_db_data


def read_blob_data(shot,
                   time_range,
                   calculate_only=False,
                   nocalc=True,
                   min_structure_lifetime=20,
                   recalc_tracking=False,
                   str_finding_method='watershed',
                   max_gap=1,
                   verbose=False,
                   ):
    """
    Wrapper function for executing `analyze_gpi_structures` with pre-configured defaults.

    This function simplifies the execution of the main GPI structure analysis routine 
    by exposing only the essential configuration parameters. It pre-sets the majority 
    of the underlying mathematical, tracking, and plotting flags to values optimized 
    for processing standard Gas Puff Imaging "blob" data.

    Args:
        shot (float or int): The experiment or shot number to analyze.
        time_range (list or tuple): The [start, end] time range for the calculation.
        calculate_only (bool, optional): If True, suppresses the returning of the 
            results dictionary and skips any remaining plotting instructions. 
            Defaults to False.
        nocalc (bool, optional): Switch for not recalculating already existing 
            results. If True, attempts to load data from an existing `.pickle` file. 
            Defaults to True.
        min_structure_lifetime (int, optional): Minimum required lifetime in frames 
            for a structure to be kept. Identified structures living shorter than 
            this will be dropped. Defaults to 20 (approx. 50us).
        recalc_tracking (bool, optional): If True, recalculates the tracking matrices 
            and paths without recalculating the underlying image segmentation. 
            Defaults to False.
        str_finding_method (str, optional): The mathematical method used for structure 
            identification and segmentation (either 'watershed' or 'contour'). 
            Defaults to 'watershed'.
        max_gap (int, optional): The maximum number of "missing" frames allowed 
            when tracking a structure to bridge segmentation errors. Defaults to 1.
        verbose (bool, optional): If False, suppresses standard output messages, 
            which is useful for keeping the console clean during long batch calculations. 
            Defaults to False.

    Returns:
        dict or None: 
            - If `calculate_only` is False and the analysis succeeds, returns a 
              dictionary containing the structured data (`{'data', 'time', 'structures'}`).
            - If `calculate_only` is True, or if an exception is caught during 
              execution, returns None.
    """
    
    try:
    # if True:
        blob_results = analyze_gpi_structures(exp_id=shot,
                                              time_range=time_range,
                                              normalize='simple',
                                              str_finding_method=str_finding_method,
                                              threshold_bg_multiplier=2.,
                                              ellipse_method='linalg',
                                              fit_shape='ellipse',
                                              smooth_contours=5,
                                              
                                              tracking='weighted',
                                              matrix_weight={'iou':1,'cccf':0},
                                              ignore_side_structures=True,
                                              remove_orphans=True,
                                              max_gap=max_gap,
                                              min_structure_lifetime=min_structure_lifetime,
                                              tracking_assignment='max_score',      #Method of assigning the correspondence, 'hungarian' or 'max_score'
                                              score_threshold=0.7,
                                              
                                              nocalc=nocalc,
                                              recalc_tracking=recalc_tracking,
                                              structure_pixel_calc=False,
                                              fix_structure_angles=True,
                                              
                                              test_structures=False,
                                              return_results=not calculate_only,
                                              
                                              plot=False,
                                              plot_str_by_str=True,
                                              plot_scatter=True,
                                              plot_tracking=True,
                                              calculate_rough_diff_velocities=False,
                                              plot_for_publication=True,
                                              pdf=False,
                                              structure_pdf_save=False,
                                              structure_video_save=False,
                                              test=False,
                                              verbose=verbose,
                                              )
        if not calculate_only:
            return blob_results

    except Exception as e:
       print('Exception in read_data_for_analyze_blob_database.py line 345.')
       print(e)
       print(f"Couldn't calculate {shot}, at {time_range} seconds.")
       
       if not calculate_only:
           return None


def read_blob_database_file(time_range_around_peak=5e-3,
                            blob_db_file='/Users/mlampert/work/NSTX_workspace/db/2010.csv',
                            elm_db_file='/Users/mlampert/work/NSTX_workspace/db/ELM_findings_mlampert_velocity_good.csv',
                            nofilter=False
                            ):
    """
    Reads a blob database and optionally filters it against an ELM database.

    (generated by Gemini)

    This function imports a CSV containing experimental blob data, selecting only 
    entries with a specific quality assessment flag (column index 2 == 0). If 
    filtering is enabled, it cross-references these shots with an ELM database. 
    If a blob's peak time falls within the start and end times of ELMs for that 
    shot, the blob's timestamp is shifted outside the ELM window (padded by 
    `time_range_around_peak`). Finally, it filters out older shots (<= 138127).

    Args:
        time_range_around_peak (float, optional): The time padding (in seconds) 
            Defaults to 5e-3.
        blob_db_file (str, optional): Absolute filepath to the CSV containing 
            the blob database. Defaults to 
            '/Users/mlampert/work/NSTX_workspace/db/2010.csv'.
        elm_db_file (str, optional): Absolute filepath to the CSV containing 
            the ELM database. Defaults to 
            '/Users/mlampert/work/NSTX_workspace/db/ELM_findings_mlampert_velocity_good.csv'.
        nofilter (bool, optional): If False, applies ELM overlap shifting and 
            removes specific shots (<= 138127). If True, skips the ELM overlap 
            filtering entirely. Defaults to False.

    Returns:
        dict: A dictionary containing the filtered database:
            - 'shot' (numpy.ndarray): Array of valid shot numbers.
            - 'time' (numpy.ndarray): Array of adjusted peak times (in seconds).
    """

    if isinstance(time_range_around_peak, (list, np.ndarray)):
        raise TypeError('time_range_around_peak should be a float in this reading routine.')

    # Read blob database
    database = np.asarray(pandas.read_csv(blob_db_file))
    
    # Extract the actual 1D array of indices from the np.where tuple
    ind_shots = np.where(database[:, 2] == 0)[0] 
    
    blob_shots = database[ind_shots, 0]
    peak_times = database[ind_shots, 1] / 1000.  # Convert to seconds
    
    blob_database = {'shot': blob_shots,
                     'time': peak_times}

    if not nofilter:
        # Read ELM database
        db = pandas.read_csv(elm_db_file, index_col=0)
        elm_shots = np.asarray(db)[:, 1]
        elm_times = np.asarray(db)[:, 3]
        
        # Create a boolean mask to safely flag which blobs to drop without messing up the loop index
        keep_mask = np.ones(len(blob_database['shot']), dtype=bool)

        for i, shot_blob in enumerate(blob_database['shot']):
            ind_overlap = np.where(elm_shots == shot_blob)[0]
            original_blob_time = blob_database['time'][i]
            
            if len(ind_overlap) > 0:
                current_elm_times = elm_times[ind_overlap]
                min_time = np.min(current_elm_times)
                max_time = np.max(current_elm_times)
                
                # If the blob falls exactly within the ELM boundaries
                if min_time < original_blob_time < max_time:
                    if abs(original_blob_time - min_time) < abs(original_blob_time - max_time):
                        blob_database['time'][i] = min_time - 2 * time_range_around_peak
                    else:
                        blob_database['time'][i] = max_time + 2 * time_range_around_peak
                        
                # Check if the new time is shifted by more than 50ms from the original time
                if abs(blob_database['time'][i] - original_blob_time) > 50e-3:
                    keep_mask[i] = False  # Flag for removal instead of popping

        # Apply the mask to drop invalid blobs all at once
        blob_database['shot'] = blob_database['shot'][keep_mask]
        blob_database['time'] = blob_database['time'][keep_mask]

        # Final filter to keep only newer shots
        ind_newer = np.where(blob_database['shot'] > 138127)[0]
        blob_database['shot'] = blob_database['shot'][ind_newer]
        blob_database['time'] = blob_database['time'][ind_newer]

    return blob_database


def read_blob_lh_mode_database_file(l_mode=False,
                                    h_mode=False,
                                    filtered_blob_db=True, #filter the database to shots read by read_blob_database
                                    time_range_around_peak=None,
                                    filter_lh_transition=False,
                                    filter_elms=False,
                                    ):
    """
    Reads and filters a shot database specifically for L-mode or H-mode experiments.

    This function loads a comprehensive database ('db/2010_all.csv') and filters 
    it based on the 'comments by Ricky' column to isolate either L-mode or H-mode 
    shots. 
    
    The function operates in two primary modes:
    1. Filtered (`filtered_blob_db=True`): It cross-references the isolated L/H-mode 
       shots against the standard blob database (loaded via `read_blob_database_file`), 
       inheriting its strict ELM and quality filtering automatically.
    2. Unfiltered (`filtered_blob_db=False`): It applies its own filtering logic 
       directly to the '2010_all.csv' data, keeping only shots with a 'movie rating' 
       of 'A' or 'A+'. It can also optionally drop shots containing L-H transitions 
       or overlapping ELMs within the specified time window.

    Args:
        l_mode (bool, optional): If True, isolates shots marked as 'L-mode'. 
            Defaults to False.
        h_mode (bool, optional): If True, isolates shots marked as 'H-mode'. 
            Defaults to False.
        filtered_blob_db (bool, optional): If True, intersects the L/H mode shots 
            with the highly curated `read_blob_database_file` output. If False, 
            relies on manual movie ratings and custom time boundaries. Defaults to True.
        time_range_around_peak (float or list, optional): The time window to process 
            around a peak event. Used for shifting time ranges away from ELMs.
            - If float: The range is `[peak - range, peak + range]`.
            - If list: The range is `[peak - range[0], peak + range[1]]`.
            Defaults to None.
        filter_lh_transition (bool, optional): If True (and `filtered_blob_db=False`), 
            drops any shot that contains recorded L-H or H-L transition times. 
            Defaults to False.
        filter_elms (bool, optional): If True (and `filtered_blob_db=False`), drops 
            any shot where an ELM event overlaps with the calculated analysis time 
            window. Defaults to False.

    Raises:
        ValueError: If neither `l_mode` nor `h_mode` is set to True.

    Returns:
        dict: A dictionary containing the filtered database:
            - 'shot' (list or numpy.ndarray): Valid shot numbers.
            - 'time' (list or numpy.ndarray): Corresponding peak times (if 
              `time_range_around_peak` is None) OR a 2D array of [start, end] 
              time ranges (if `time_range_around_peak` is provided).
    """
    
    all_db_file = '/Users/mlampert/work/NSTX_workspace/db/2010_all.csv'
    
    if l_mode:
        find_string = 'L-mode'
    elif h_mode:
        find_string = 'H-mode'
    else:
        raise ValueError('Either l_mode or h_mode needs to be set.')
    
    all_database = pandas.read_csv(all_db_file)
    all_database['peak GPI time (ms)'] /= 1e3
    
    # Cast comments to string in case of NaNs in the CSV, then find indices
    comments = all_database['comments by Ricky'].astype(str)
    lh_mode_shot_inds = np.array([ind for ind, item in enumerate(comments) if find_string in item])
    lh_mode_shots = all_database['shot'].values[lh_mode_shot_inds]
    
    if filtered_blob_db:
        # Cross-reference with the previously built database
        if isinstance(time_range_around_peak, (list,np.ndarray)):
            time_range_around_peak = np.mean(time_range_around_peak)
        blob_db = read_blob_database_file(time_range_around_peak=time_range_around_peak if time_range_around_peak is not None else 5e-3)
        blob_shots = blob_db['shot']
        blob_times = blob_db['time']
            
        # Keep only the shots that exist in BOTH databases
        valid_mask = np.isin(blob_shots, lh_mode_shots)
        lh_mode_shots_in_blob_db = blob_shots[valid_mask]
        lh_mode_times_in_blob_db = blob_times[valid_mask]
        
        database = {'shot': lh_mode_shots_in_blob_db,
                    'time': lh_mode_times_in_blob_db}
        
    else:
        # Apply custom filtering
        # 1. Filter by movie rating ('A' or 'A+')
        movie_ratings = all_database['movie rating'].values[lh_mode_shot_inds]
        rating_mask = np.isin(movie_ratings, ['A', 'A+'])
        lh_mode_shot_inds = lh_mode_shot_inds[rating_mask]

        if isinstance(time_range_around_peak, (int, float)):
            time_range_around_peak = [time_range_around_peak, time_range_around_peak]

        if time_range_around_peak is not None:
            
            # 2. Filter L-H and H-L transitions
            if filter_lh_transition:
                lh_times = all_database['L-H time'].values[lh_mode_shot_inds]
                hl_times = all_database['H-L time'].values[lh_mode_shot_inds]
                
                # Keep only rows where BOTH transition times are NaN (no transition occurred)
                transition_mask = np.isnan(lh_times) & np.isnan(hl_times)
                lh_mode_shot_inds = lh_mode_shot_inds[transition_mask]
                
            # 3. Filter ELMs overlap
            if filter_elms:
                elm_times = all_database['ELM time'].values[lh_mode_shot_inds]
                peak_times = all_database['peak GPI time (ms)'].values[lh_mode_shot_inds]
                
                # Find where ELMs overlap the window exactly
                elm_overlap_mask = (elm_times > (peak_times - time_range_around_peak[0])) & \
                                   (elm_times < (peak_times + time_range_around_peak[1]))
                
                # Keep the indices where there is NO overlap
                lh_mode_shot_inds = lh_mode_shot_inds[~elm_overlap_mask]


                        # if (np.abs(all_database['ELM time'][ind]-(all_database['peak signal'][ind])-time_range_around_peak)<
                        #     (all_database['peak signal'][ind])+time_range_around_peak-np.abs(all_database['ELM time'][ind])):
                        #     database['time'][0,ind_index]=all_database['ELM time'][ind]
                        # else:
                        #     database['time'][1,ind_index]=all_database['ELM time'][ind]

            # Construct final database using only the surviving indices
            final_shots = all_database['shot'].values[lh_mode_shot_inds]
            final_peaks = all_database['peak GPI time (ms)'].values[lh_mode_shot_inds]
            
            database = {
                'shot': final_shots,
                'time': np.array([final_peaks - time_range_around_peak[0], 
                                  final_peaks + time_range_around_peak[1]]).T
            }

        else:   
            database = {
                'shot': all_database['shot'].values[lh_mode_shot_inds],
                'time': all_database['peak GPI time (ms)'].values[lh_mode_shot_inds]
            }
        
    return database



def read_all_plasma_data(time_range_around_peak=5e-3,
                         nocalc=False,
                         read_l_mode_only=False,
                         read_h_mode_only=False,
                         calculate_parameters_in_sol=False,
                         ):
    """
    Retrieves and aggregates bulk plasma parameters across a database of experimental shots.

    This function reads the specified blob database (either full, L-mode only, or 
    H-mode only) to determine the valid shots and their corresponding peak times. 
    It then fetches the core or Scrape-Off Layer (SOL) plasma parameters for each 
    shot at that specific time using the `read_plasma_data` routine. The aggregated 
    results are cached in a `.pickle` file to speed up subsequent executions.

    Args:
        time_range_around_peak (float, optional): The time padding (in seconds) 
            used to shift the analysis time away from overlapping ELMs when loading 
            the initial blob databases. Defaults to 5e-3.
        nocalc (bool, optional): If True, attempts to skip the data fetching loop 
            and directly load the aggregated plasma parameters from a cached 
            `.pickle` file. Defaults to False.
        read_l_mode_only (bool, optional): If True, restricts the data fetching 
            to shots identified as L-mode. Defaults to False.
        read_h_mode_only (bool, optional): If True, restricts the data fetching 
            to shots identified as H-mode. Defaults to False.
        calculate_parameters_in_sol (bool, optional): If True, fetches the plasma 
            parameters specifically from the Scrape-Off Layer (SOL) rather than 
            the core plasma. Appends '_sol' to the cache filename. Defaults to False.

    Returns:
        dict: A dictionary containing the aggregated plasma parameters across all 
            processed shots. The keys correspond to the specific plasma parameters 
            returned by `read_plasma_data` (e.g., electron density, temperature), 
            and the values are 1D NumPy arrays containing the values for each shot.
    """
    
    
    
    pickle_filename_plasma_l_mode=wd+'/processed_data/plasma_vs_blob_plasma_data_l_mode'
    pickle_filename_plasma_h_mode=wd+'/processed_data/plasma_vs_blob_plasma_data_h_mode'
    
    if read_l_mode_only:
        pickle_filename=pickle_filename_plasma_l_mode
    elif read_h_mode_only:
        pickle_filename=pickle_filename_plasma_h_mode
    else:
        pickle_filename=wd+'/processed_data/plasma_vs_blob_plasma_data_full'
    if calculate_parameters_in_sol:
        pickle_filename+='_sol'
        
    pickle_filename+='.pickle'
    
    # pickle_filename=wd+'/processed_data/blob_database_shot_by_shot_plasma.pickle'
    if read_l_mode_only:
        blob_database=read_blob_lh_mode_database_file(l_mode=True,
                                                      time_range_around_peak=time_range_around_peak)
    elif read_h_mode_only:
        blob_database=read_blob_lh_mode_database_file(h_mode=True,
                                                      time_range_around_peak=time_range_around_peak)
    else:
        blob_database=read_blob_database_file(time_range_around_peak=time_range_around_peak,)

    if (not os.path.exists(pickle_filename) or not nocalc):
        # or read_l_mode_only or read_h_mode_only or calculate_parameters_in_sol):
        
    # if True:
        ncalc=len(blob_database['shot'])

        curr_plasma_data=read_plasma_data(exp_id=blob_database['shot'][0],
                                          time=blob_database['time'][0],
                                          calculate_parameters_in_sol=calculate_parameters_in_sol)
        full_plasma_data={}
        for key in curr_plasma_data:
            full_plasma_data[key]=[]

        for ind in range(ncalc):
            blob_time=blob_database['time'][ind]
            shot=blob_database['shot'][ind]

            curr_plasma_data=read_plasma_data(exp_id=shot,
                                              time=blob_time,
                                              calculate_parameters_in_sol=calculate_parameters_in_sol)
            for key in curr_plasma_data.keys():
                full_plasma_data[key]=np.append(full_plasma_data[key],
                                                curr_plasma_data[key])
                
        
        pickle.dump(full_plasma_data,open(pickle_filename,'wb'))
    else:
        full_plasma_data=pickle.load(open(pickle_filename,'rb'))
        
    return full_plasma_data


def read_plasma_parameters_for_table_in_paper(database=None,
                                              print_ranges=False):
    """
    Extracts key global plasma parameters across a database of shots for summary tables.

    This function iterates through a given database of experimental shots and their 
    corresponding times. For each event, it retrieves the core plasma parameters 
    (collisionality, q95, Greenwald fraction, plasma current, toroidal field, and 
    line-integrated density) using the `read_plasma_data` routine. It also generates 
    and saves diagnostic PDF plots for the density and temperature profile fits.

    Args:
        database (dict, optional): A dictionary containing 'shot' and 'time' arrays. 
            If None, it automatically loads the default blob database via 
            `read_blob_database_file()`. Defaults to None.
        print_ranges (bool, optional): If True, calculates and prints the minimum 
            and maximum values for each of the extracted parameters to the console 
            after the loop completes. Defaults to False.

    Returns:
        tuple: A tuple containing six lists of the extracted parameters in the 
            following order:
            - collisionality (list): Average collisionality for each shot.
            - q95 (list): Safety factor at the 95% flux surface for each shot.
            - greenwald (list): Greenwald density fraction for each shot.
            - current (list): Plasma current for each shot.
            - btoroidal (list): Toroidal magnetic field for each shot.
            - density (list): Line-integrated density for each shot.
    """
    
    if database is None:
        database=read_blob_database_file()

    density=[]
    current=[]
    btoroidal=[]
    greenwald=[]
    collisionality=[]
    q95=[]
    pdf_pages_density=PdfPages(wd+'/plots/blob_database_density_fits.pdf')
    pdf_pages_temperature=PdfPages(wd+'/plots/blob_database_temperature_fits.pdf')

    for ind_shot in range(len(database['shot'])):
        print(f"\r{ind_shot/len(database['shot'])*100} % done from the calculation.", flush=True, end='')
        time_curr=database['time'][ind_shot]
        shot=database['shot'][ind_shot]

        start_time=time_mod.time()

        plasma_parameters=read_plasma_data(exp_id=shot,time=time_curr,
                                                 pdf_pages_density=pdf_pages_density,
                                                 pdf_pages_temperature=pdf_pages_temperature)

        greenwald.append(plasma_parameters['Greenwald fraction'])
        density.append(plasma_parameters['Line integrated density'])
        q95.append(plasma_parameters['q95'])
        current.append(plasma_parameters['Current'])

        btoroidal.append(plasma_parameters['Toroidal field'])
        collisionality.append(plasma_parameters['Collisionality'])
        # print(str((ind_shot+1)/len(database['shot'])*100.)+'% done')
        print('Finished in: ',time_mod.time()-start_time,'s')

    if print_ranges:
        print('Collisionality range: ',min(collisionality),max(collisionality))
        print('Density range: ',min(density), max(density))
        print('Greenwald range: ',min(greenwald),max(greenwald))
        print('BT range: ',min(btoroidal),max(btoroidal))
        print('current range: ',min(current),max(current))

    pdf_pages_density.close()
    pdf_pages_temperature.close()

    return collisionality, q95, greenwald, current, btoroidal, density

def read_plasma_data(exp_id=None,
                     time=None,
                     pdf_pages_density=None,
                     pdf_pages_temperature=None,
                     calculate_parameters_in_sol=False,
                     temperature_threshold=5e-3
                     ):
    """
    Retrieves and calculates fundamental plasma parameters for a specific shot and time.

    This function pulls electron density, temperature, and pressure profiles from 
    Thomson scattering data, fits them to extract core and Scrape-Off Layer (SOL) 
    characteristics, and queries the MDSplus database for magnetic geometries and 
    global parameters. Finally, it derives key physics quantities such as collisionality, 
    Larmor radii, plasma frequencies, and the Greenwald fraction.

    Args:
        exp_id (int, optional): The experimental shot number to analyze. Defaults to None.
        time (float, optional): The time step (in seconds) to slice the data. Defaults to None.
        pdf_pages_density (PdfPages, optional): A matplotlib PdfPages object to save 
            density profile fit plots. Defaults to None.
        pdf_pages_temperature (PdfPages, optional): A matplotlib PdfPages object to save 
            temperature and pressure profile fit plots. Defaults to None.
        calculate_parameters_in_sol (bool, optional): If True, uses the SOL average values 
            for density and temperature instead of the peak profile values. Note that 
            uncertainty is generally higher in the SOL. Defaults to False.
        temperature_threshold (float, optional): The minimum allowed SOL temperature 
            in keV (default 5e-3, or 5 eV). Temperatures below this imply a detached 
            plasma; if encountered, the value is forced to NaN. Defaults to 5e-3.

    Returns:
        dict: A comprehensive dictionary containing raw profile characteristics, MDSplus 
            geometric data, and derived fundamental plasma physics parameters.
    """

    # --- 1. Thomson Profile Fetching & Fitting ---
    # Bundle the repeated arguments into a dictionary
    thomson_kwargs = {
        'exp_id': exp_id,
        'spline_data': True,
        'modified_tanh': False,
        'outboard_only': False,
        'device_coordinates': True,
        'radial_range': [1.3, 1.55],
        'plot_time_vec': time
    }

    ne_params = get_fit_nstx_thomson_profiles(density=True, pdf_object=pdf_pages_density, **thomson_kwargs)
    te_params = get_fit_nstx_thomson_profiles(temperature=True, pdf_object=pdf_pages_temperature, **thomson_kwargs)
    pe_params = get_fit_nstx_thomson_profiles(pressure=True, pdf_object=pdf_pages_temperature, **thomson_kwargs)

    ind = np.argmin(np.abs(ne_params['time_vec'] - time))

    # --- 2. Determine Core vs. SOL parameters ---
    if calculate_parameters_in_sol:
        n_e = ne_params['SOL avg'][ind]
        T_e = te_params['SOL avg'][ind] 
        if T_e < temperature_threshold: 
            T_e = np.nan
    else:
        n_e = ne_params['Value at max'][ind]
        T_e = te_params['Value at max'][ind] # In keV
    
    T_i = T_e # TODO: should be read from CHERS
    R_pressure_max_grad = pe_params['Position r'][ind]

    # --- 3. Internal Helper for MDSPlus Data ---
    
    def _fetch_mds(node, r_target=None):
        """Safely fetches and slices MDSPlus data, returning np.nan on failure."""
        try:
            d = flap.get_data('NSTX_MDSPlus', name=node, exp_id=exp_id).slice_data(slicing={'Time': time})
            if r_target is not None:
                d = d.slice_data(slicing={'Device R': r_target})
            return np.mean(d.data)
        except Exception as e:
            print(f"Failed to read {node} for shot {exp_id}: {e}")
            return np.nan

    # Fetch scalar MDSPlus values
    current       = _fetch_mds(r'\EFIT02::\IPMEAS')
    b_toroidal    = _fetch_mds(r'\EFIT02::\BT0')
    minor_radius  = _fetch_mds(r'\EFIT02::\AMINOR')
    R_separatrix  = _fetch_mds(r'\EFIT02::\RMIDOUT') - 0.02
    q95           = _fetch_mds(r'\EFIT02::\Q95')
    lower_triang  = _fetch_mds(r'\EFIT02::\TRIBOT')
    upper_triang  = _fetch_mds(r'\EFIT02::\TRITOP')
    elongation    = _fetch_mds(r'\EFIT02::\KAPPA')
    inner_gap     = _fetch_mds(r'\EFIT02::\GAPIN')
    outer_gap     = _fetch_mds(r'\EFIT02::\GAPOUT')
    cdens_95      = _fetch_mds(r'\EFIT02::\J95N')
    cdens_99      = _fetch_mds(r'\EFIT02::\J99N')
    q_boundary    = _fetch_mds(r'\EFIT02::\QL')
    R_mag_axis    = _fetch_mds(r'\EFIT02::\RMAXIS')
    z_outer_sp    = _fetch_mds(r'\EFIT02::\ZVSOUT')
    R_outer_sp    = _fetch_mds(r'\EFIT02::\RVSOUT')
    R_lower_xpt   = _fetch_mds(r'\EFIT02::\RXPT1')
    z_lower_xpt   = _fetch_mds(r'\EFIT02::\ZXPT1')

    # Fetch spatial MDSPlus values at max pressure gradient
    B_tor_grad = _fetch_mds(r'\EFIT02::\BTZ0', r_target=R_pressure_max_grad)
    B_pol_grad = _fetch_mds(r'\EFIT02::\BZZ0', r_target=R_pressure_max_grad)
    B_rad_grad = _fetch_mds(r'\EFIT02::\BRZ0', r_target=R_pressure_max_grad)
    magnetic_field = np.sqrt(B_tor_grad**2 + B_pol_grad**2 + B_rad_grad**2)

    # Fetch spatial MDSPlus values at separatrix for connection length
    B_tor_sep = _fetch_mds(r'\EFIT02::\BTZ0', r_target=R_separatrix)
    B_pol_sep = _fetch_mds(r'\EFIT02::\BZZ0', r_target=R_separatrix)

    # --- 4. Line Integrated Density ---
    try:
        d_ne = flap.get_data('NSTX_THOMSON', exp_id=exp_id, name='', object_name='THOMSON_DATA', 
                             options={'pressure':False, 'temperature':False, 'density':True, 
                                      'spline_data':False, 'add_flux_coordinates':False, 'force_mdsplus':False})
        ind_lid = np.argmin(np.abs(d_ne.coordinate('Time')[0][1,:] - time))
        norm_factor = np.max(d_ne.coordinate('Device R')[0][:,:], axis=0) - np.min(d_ne.coordinate('Device R')[0][:,:], axis=0)
        density = (np.trapz(d_ne.data[:,:], d_ne.coordinate('Device R')[0][:,:], axis=0) / norm_factor)[ind_lid]
    except Exception as e:
        print(f"Failed to read LID for shot {exp_id}: {e}")
        density = np.nan

    # --- 5. Physics Derived Parameters ---
    gamma = 1.0
    Z = 1.0
    ln_LAMBDA = 17
    m_i = 2.014 * 1.66e-27       # Deuterium mass (kg)
    m_e = 9.1093835e-31          # Electron mass (kg)
    q_e = 1.6e-19                # Elementary charge (C)
    k_B = 1.38e-23               # Boltzmann constant
    epsilon_0 = 8.854e-12        # Vacuum permittivity

    omega_pe = np.sqrt(n_e * q_e**2 / m_e / epsilon_0)
    omega_pi = np.sqrt(n_e * q_e**2 / m_i / epsilon_0)
    
    # Sound speed (convert T_e from keV to eV internally via 1e3)
    c_s = np.sqrt(gamma * Z * k_B * T_e * 1e3 * 11606 / m_i) 

    rho_e = 2.384e-6 * np.sqrt(T_e * 1e3) / magnetic_field
    rho_i = 1.019e-4 * np.sqrt(T_i * 1e3) / magnetic_field
    rho_s = rho_i

    ei_collision_rate = 2.9e-12 * n_e * Z**2 * ln_LAMBDA / ((T_e * 1e3)**(3/2))

    inverse_aspect = minor_radius / R_separatrix
    collisionality = ei_collision_rate * q95 * R_separatrix / c_s / inverse_aspect**1.5
    greenwald_fraction = density / (current / (np.pi * minor_radius**2) * 1e14)

    # Connection Length Calculation
    try:
        connection_length = np.sqrt((np.abs(z_outer_sp) * np.sqrt(B_pol_sep**2 + B_tor_sep**2) / B_pol_sep)**2 + 
                                    ((R_separatrix - R_lower_xpt) + (R_outer_sp - R_lower_xpt))**2)
        if connection_length < 1.5: 
            connection_length = np.nan
    except Exception as e:
        print(f"Failed to calculate connection length for shot {exp_id}: {e}")
        connection_length = np.nan

    omega_gyro_electron = q_e * np.abs(B_tor_grad) / m_e
    omega_gyro_ion = q_e * np.abs(B_tor_grad) / m_i
    
    collisionality_dimless = ei_collision_rate * connection_length / rho_s / omega_gyro_electron

    # --- 6. Compile Return Dictionary ---
    return {
        'Line integrated density': density,
        'Current': current,
        'Greenwald fraction': greenwald_fraction,
        'Toroidal field': b_toroidal,
        'Collision rate ei': ei_collision_rate,
        
        'Collisionality': collisionality,
        'Collisionality dimensionless': collisionality_dimless,
        'Connection length': connection_length,
        'q95': q95,
        'q boundary': q_boundary,
        
        'Magnetic field toroidal': B_tor_sep,
        'Magnetic field poloidal': B_pol_sep,
        'Magnetic field radial': B_rad_grad, 
        'Magnetic field absolute': magnetic_field,
        
        'Outer strike point R': R_outer_sp,
        'Outer strike point z': z_outer_sp,
        'Lower x point R': R_lower_xpt,
        'Lower x point z': z_lower_xpt,
        
        'Sound speed': c_s,
        'Plasma frequency': omega_pe,
        'Plasma frequency electron': omega_pe,
        'Plasma frequency ion': omega_pi,
        
        'Plasma elongation': elongation,
        'Plasma triangularity upper': upper_triang,
        'Plasma triangularity lower': lower_triang,
        'Plasma triangularity': (upper_triang + lower_triang) / 2,
        
        'Minor radius': minor_radius,
        'Magnetic axis radius': R_mag_axis,
        'Pedestal radius': R_separatrix,
        'Larmor radius': rho_e,
        'Larmor radius electron': rho_e,
        'Larmor radius ion': rho_i,
        'Larmor radius sound': rho_s,
        'Larmor frequency electron': omega_gyro_electron,
        'Larmor frequency ion': omega_gyro_ion,
        
        'Inner gap': inner_gap,
        'Outer gap': outer_gap,
        'Current density at 95': cdens_95,
        'Current density at 99': cdens_99,
        
        'Density at max': ne_params['Value at max'][ind],
        'Density pedestal height': ne_params['Height'][ind],
        'Density SOL offset': ne_params['SOL offset'][ind],
        'Density pedestal position': ne_params['Position'][ind],
        'Density pedestal width': ne_params['Width'][ind],
        'Density max gradient': ne_params['Max gradient'][ind],
        'Density SOL': n_e,
        
        'Temperature at max': te_params['Value at max'][ind],
        'Temperature pedestal height': te_params['Height'][ind],
        'Temperature SOL offset': te_params['SOL offset'][ind],
        'Temperature pedestal position': te_params['Position'][ind],
        'Temperature pedestal width': te_params['Width'][ind],
        'Temperature max gradient': te_params['Max gradient'][ind],
        'Temperature SOL': T_e,
        
        'Pressure at max': pe_params['Value at max'][ind],
        'Pressure pedestal height': pe_params['Height'][ind],
        'Pressure SOL offset': pe_params['SOL offset'][ind],
        'Pressure pedestal position': pe_params['Position'][ind],
        'Pressure pedestal width': pe_params['Width'][ind],
        'Pressure max gradient': pe_params['Max gradient'][ind],   
        'Pressure SOL': n_e * T_e,
    }

def read_plasma_data_old(exp_id=None,
                     time=None,
                     pdf_pages_density=None,
                     pdf_pages_temperature=None,
                     calculate_parameters_in_sol=False,
                     temperature_threshold=5e-3 #5eV threshold for SOL temperature, below plasma would be detached which it isn't
                     ):
    """
    Reads all important plasma parameters from the MDSplus database.

    Parameters
    ----------
    exp_id : integer, optional
        Shot number. The default is None.
    time : float, optional
        Time of the plasma parameter to be calculated. The default is None.
    pdf_pages_density : PdfPages matplotlib object, optional
        PDFpages matplotlib object for plotting the density profiles. The default is None.
    pdf_pages_temperature : PdfPages matplotlib object, optional
        PdfPages matplotlib object for plotting the density profiles. The default is None.
    calculate_parameters_in_sol : boolean, optional
        Switch for calculating parameters in the SOL. Here, uncertainty is high. The default is False.
    temperature_threshold : TYPE, optional
        #5eV threshold for SOL temperature, below plasma would be detached which it isn't. The default is 5e-3.

    Returns
    -------
    dict
        Dictionary with the plasma parameters.

    """

    #THESE READ THE ENTIRE SHOT"S PROFILES AND FIT THEM
    ne_params=get_fit_nstx_thomson_profiles(exp_id=exp_id,
                                            density=True,
                                            spline_data=True,
                                            modified_tanh=False,
                                            outboard_only=False,

                                            #flux_coordinates=True,
                                            # flux_range=[0.7,1.1],
                                            device_coordinates=True,
                                            radial_range=[1.3,1.55],
                                            pdf_object=pdf_pages_density,
                                            plot_time_vec=time
                                            )

    te_params=get_fit_nstx_thomson_profiles(exp_id=exp_id,
                                            temperature=True,
                                            spline_data=True,
                                            modified_tanh=False,
                                            outboard_only=False,

                                            #flux_coordinates=True,
                                            # flux_range=[0.7,1.1],
                                            device_coordinates=True,
                                            radial_range=[1.3,1.55],
                                            pdf_object=pdf_pages_temperature,
                                            plot_time_vec=time
                                            )
    
    pe_params=get_fit_nstx_thomson_profiles(exp_id=exp_id,
                                            pressure=True,
                                            spline_data=True,
                                            modified_tanh=False,
                                            outboard_only=False,

                                            #flux_coordinates=True,
                                            # flux_range=[0.7,1.1],
                                            device_coordinates=True,
                                            radial_range=[1.3,1.55],
                                            pdf_object=pdf_pages_temperature,
                                            plot_time_vec=time
                                            )
    
    ind=np.argmin(np.abs(ne_params['time_vec']-time))
    
    if calculate_parameters_in_sol:
        n_e=ne_params['SOL avg'][ind]
        T_e=te_params['SOL avg'][ind] #to convert from keV to Kelvins
        if T_e < temperature_threshold: T_e=np.nan
    else:
        n_e=ne_params['Value at max'][ind]
        T_e=te_params['Value at max'][ind] #This is in keV
    
    T_i=T_e                                                                     #TODO: should be read from CHERS
    
    R_pressure_max_grad=pe_params['Position r'][ind]
    
    """Line integrated density"""
    try:
        d_ne=flap.get_data('NSTX_THOMSON',
                        exp_id=exp_id,
                        name='',
                        object_name='THOMSON_DATA',
                        options={'pressure':False,
                                 'temperature':False,
                                 'density':True,
                                 'spline_data':False,
                                 'add_flux_coordinates':False,
                                 'force_mdsplus':False})

        ind=np.argmin(np.abs(d_ne.coordinate('Time')[0][1,:]-time))

        #goodind=np.where(np.logical_and(d_ne.coordinate('Flux r')[0][:,elm_index] < 1.0, d_ne.coordinate('Flux r')[0][:,elm_index] > 0))
        # dR = (d_ne.coordinate('Device R')[0][:,:]-
        #       np.insert(d_ne.coordinate('Device R')[0][0:-1,:],0,0,axis=0))
        norm_factor=(np.max(d_ne.coordinate('Device R')[0][:,:],axis=0)-
                     np.min(d_ne.coordinate('Device R')[0][:,:],axis=0))

        density=(np.trapz(d_ne.data[:,:],
                          d_ne.coordinate('Device R')[0][:,:],
                          axis=0)/norm_factor)[ind]
        #LID=np.sum(((d_ne.data[:,:])[:,:])*dR,axis=0)/np.sum(dR)
    except Exception as e:
        print(e)
        print('Failed to read LID for shot ',exp_id)
        density=np.nan

    """Plasma current"""
    try:
        current=np.mean(flap.get_data('NSTX_MDSPlus',
                                      name='\EFIT02::\IPMEAS',
                                      exp_id=exp_id,
                                      ).slice_data(slicing={'Time':time}).data)
    except Exception as e:
        print(e)
        print('Failed to read current for shot ',exp_id)
        current=np.nan

    """Toroidal field"""
    try:
        b_toroidal=np.mean(flap.get_data('NSTX_MDSPlus',
                                      name='\EFIT02::\BT0',
                                      exp_id=exp_id,
                                      ).slice_data(slicing={'Time':time}).data)
    except Exception as e:
        print(e)
        print('Failed to read Bt for shot ',exp_id)
        b_toroidal=np.nan

    """Minor radius"""
    try:
        minor_radius=flap.get_data('NSTX_MDSPlus',
                              name='\EFIT02::\AMINOR',
                              exp_id=exp_id,
                              ).slice_data(slicing={'Time':time}).data
    except Exception as e:
        print(e)
        print('Failed to read current for shot ',exp_id)
        minor_radius=np.nan

    """Pedestal radius"""
    try:
        R_separatrix=flap.get_data('NSTX_MDSPlus',
                                   name='\EFIT02::\RMIDOUT',
                                   exp_id=exp_id,
                                   ).slice_data(slicing={'Time':time}).data-0.02
    except Exception as e:
        print(e)
        print('Failed to read RMIDOUT for shot ',exp_id)
        R_separatrix=np.nan

    """Safety factor"""
    try:
        q95=flap.get_data('NSTX_MDSPlus',
                         name='\EFIT02::\Q95',
                         exp_id=exp_id,
                         ).slice_data(slicing={'Time':time}).data
    except Exception as e:
        print(e)
        print('Failed to read Q95 for shot ',exp_id)
        q95=np.nan

    """Lower triangularity"""
    try:
        lower_triang=flap.get_data('NSTX_MDSPlus',
                             name='\EFIT02::\TRIBOT',
                             exp_id=exp_id,
                             ).slice_data(slicing={'Time':time}).data
    except Exception as e:
        print(e)
        print('Failed to read TRIBOT for shot ',exp_id)
        lower_triang=np.nan

    """Upper triangularity"""
    try:
        upper_triang=flap.get_data('NSTX_MDSPlus',
                             name='\EFIT02::\TRITOP',
                             exp_id=exp_id,
                             ).slice_data(slicing={'Time':time}).data
    except Exception as e:
        print(e)
        print('Failed to read TRITOP for shot ',exp_id)
        upper_triang=np.nan

    """Elongation"""
    try:
        elongation=flap.get_data('NSTX_MDSPlus',
                             name='\EFIT02::\KAPPA',
                             exp_id=exp_id,
                             ).slice_data(slicing={'Time':time}).data
    except Exception as e:
        print(e)
        print('Failed to read KAPPA for shot ',exp_id)
        elongation=np.nan

    """Inner gap"""
    try:
        inner_gap=flap.get_data('NSTX_MDSPlus',
                             name='\EFIT02::\GAPIN',
                             exp_id=exp_id,
                             ).slice_data(slicing={'Time':time}).data
    except Exception as e:
        print(e)
        print('Failed to read GAPIN for shot ',exp_id)
        inner_gap=np.nan

    """Outer gap"""
    try:
        outer_gap=flap.get_data('NSTX_MDSPlus',
                             name='\EFIT02::\GAPOUT',
                             exp_id=exp_id,
                             ).slice_data(slicing={'Time':time}).data
    except Exception as e:
        print(e)
        print('Failed to read GAPOUT for shot ',exp_id)
        outer_gap=np.nan

    """Current density at psi_norm=0.95"""
    try:
        cdens_95=flap.get_data('NSTX_MDSPlus',
                             name='\EFIT02::\J95N',
                             exp_id=exp_id,
                             ).slice_data(slicing={'Time':time}).data
    except Exception as e:
        print(e)
        print('Failed to read J95N for shot ',exp_id)
        cdens_95=np.nan

    """Current density at psi_norm=0.99"""
    try:
        cdens_99=flap.get_data('NSTX_MDSPlus',
                             name='\EFIT02::\J99N',
                             exp_id=exp_id,
                             ).slice_data(slicing={'Time':time}).data
    except Exception as e:
        print(e)
        print('Failed to read J99N for shot ',exp_id)
        cdens_99=np.nan

    """Toroidal field"""
    try:
    # if True:
        #These read the magnetic field on the mid-plane
        B_tor=flap.get_data('NSTX_MDSPlus',
                             name='\EFIT02::\BTZ0',
                             exp_id=exp_id,
                             ).slice_data(slicing={'Time':time}).slice_data(slicing={'Device R':R_pressure_max_grad}).data
    except Exception as e:
        print(e)
        print('Failed to read B_tor for shot ',exp_id)
        B_tor=np.nan
        
    try:
        B_pol=flap.get_data('NSTX_MDSPlus',
                             name='\EFIT02::\BZZ0',
                             exp_id=exp_id,
                             ).slice_data(slicing={'Time':time}).slice_data(slicing={'Device R':R_pressure_max_grad}).data
    except Exception as e:
        print(e)
        print('Failed to read poloidal field for shot ',exp_id)
        B_pol=np.nan
        
    try:    
        B_rad=flap.get_data('NSTX_MDSPlus',
                             name='\EFIT02::\BRZ0',
                             exp_id=exp_id,
                             ).slice_data(slicing={'Time':time}).slice_data(slicing={'Device R':R_pressure_max_grad}).data
        


    except Exception as e:
        print(e)
        print('Failed to read radial magnetic field for shot ',exp_id)
        B_rad=np.nan
        
    magnetic_field = np.sqrt(B_tor**2 + B_pol**2 + B_rad**2)
        
    """Safety factor at boundary"""
    
    try:
        q_boundary=flap.get_data('NSTX_MDSPlus',
                             name='\EFIT02::\QL',
                             exp_id=exp_id,
                             ).slice_data(slicing={'Time':time}).data
    except Exception as e:
        print(e)
        print('Failed to read QL for shot ',exp_id)
        q_boundary=np.nan
    
    """Radial position of the magnetic axis"""
    
    try:
        R_mag_axis=flap.get_data('NSTX_MDSPlus',
                             name='\EFIT02::\RMAXIS',
                             exp_id=exp_id,
                             ).slice_data(slicing={'Time':time}).data
    except Exception as e:
        print(e)
        print('Failed to read RMAXIS for shot ',exp_id)
        R_mag_axis=np.nan
    
    #\FPOL	

    gamma=3/3.
    Z=1.
    m_i=2.014*1.66e-27                                               # Deuterium mass
    m_e=9.1093835e-31
    q_e=1.6e-19

    ln_LAMBDA=17

    Z=1.
    k_B=1.38e-23                                                      #Boltzmann constant

    mu0=4*np.pi*1e-7
    epsilon_0=8.854e-12
    
    """Electron plasma frequency"""
    omega_pe=np.sqrt(n_e*q_e**2/m_e/epsilon_0)

    """Ion plasma srequency"""
    omega_pi=np.sqrt(n_e*q_e**2/m_i/epsilon_0)

    """Sound speed"""
    c_s=np.sqrt(gamma*Z*k_B*T_e*1e3*11606/m_i) #=v_te
    
    """Larmor radii"""
    rho_e=2.384e-6*np.sqrt(T_e*1e3)/magnetic_field                           #Electron Larmor radius, Not rewriting because other codes might crash
    rho_i=1.019e-4*np.sqrt(T_i*1e3)/magnetic_field                           #Ion Larmor radius
    
    rho_s=rho_i
    
    n_i=n_e

    #ei_collision_rate=(n_i * Z**2 * q_e**4 * ln_LAMBDA)/(T_e**(3/2)*np.sqrt(m_e)*epsilon_0**2*16*np.pi**2)
    ei_collision_rate=2.9e-12*n_i*Z**2*ln_LAMBDA/((T_e*1e3)**(3/2))
    
    """Collisionality"""
    inverse_aspect=minor_radius/R_separatrix
    collisionality=ei_collision_rate*q95*R_separatrix/c_s/inverse_aspect**1.5

    """Greenwald fraction"""
    greenwald_fraction=density/(current.copy()/(np.pi*minor_radius**2)*1e14) #From line integrated density
    
    
    """Connection length"""
    try:
    # if True:
        #These read the magnetic field on the mid-plane
        B_tor=flap.get_data('NSTX_MDSPlus',
                             name='\EFIT02::\BTZ0',
                             exp_id=exp_id,
                             ).slice_data(slicing={'Time':time}).slice_data(slicing={'Device R':R_separatrix}).data
        
        B_pol=flap.get_data('NSTX_MDSPlus',
                             name='\EFIT02::\BZZ0',
                             exp_id=exp_id,
                             ).slice_data(slicing={'Time':time}).slice_data(slicing={'Device R':R_separatrix}).data
        
        z_outer_strike_point=flap.get_data('NSTX_MDSPlus',
                                           name='\EFIT02::\ZVSOUT',
                                           exp_id=exp_id,
                                           ).slice_data(slicing={'Time':time}).data
        
        R_outer_strike_point=flap.get_data('NSTX_MDSPlus',
                                           name='\EFIT02::\RVSOUT',
                                           exp_id=exp_id,
                                           ).slice_data(slicing={'Time':time}).data
        
        R_lower_x_point=flap.get_data('NSTX_MDSPlus',
                                      name='\EFIT02::\RXPT1',
                                      exp_id=exp_id,
                                      ).slice_data(slicing={'Time':time}).data
        
        z_lower_x_point=flap.get_data('NSTX_MDSPlus',
                                      name='\EFIT02::\ZXPT1',
                                      exp_id=exp_id,
                                      ).slice_data(slicing={'Time':time}).data
        
        connection_length=np.sqrt((np.abs(z_outer_strike_point)*np.sqrt(B_pol**2+B_tor**2)/B_pol)**2 + 
                                  ((R_separatrix-R_lower_x_point) + (R_outer_strike_point-R_lower_x_point))**2)
        
        if connection_length < 1.5: connection_length = np.nan
    except Exception as e:
        print(e)
        print('Failed to read J99N for shot ',exp_id)
        connection_length=np.nan
    
    """Electron gyrofrequency"""
    omega_gyro_electron=q_e*np.abs(B_tor)/m_e
    omega_gyro_ion=q_e*np.abs(B_tor)/m_i
    
    """Dimensionless collisionality"""
    #collisionality_dimless=1.7e-14*ne_params['Value at max'][ind]*connection_length/te_params['Value at max'][ind]**2 
    collisionality_dimless = ei_collision_rate*connection_length/rho_s/omega_gyro_electron
    

    return {'Line integrated density':density,
            
            'Current':current,
            'Greenwald fraction':greenwald_fraction,
            'Toroidal field':b_toroidal,
            'Collision rate ei':ei_collision_rate,
            
            'Collisionality':collisionality,
            'Collisionality dimensionless':collisionality_dimless,
            
            'Connection length':connection_length,
            'q95':q95,
            'q boundary':q_boundary,
            
            'Magnetic field toroidal':B_tor,                                    #at the separatrix
            'Magnetic field poloidal':B_pol,
            'Magnetic field radial':B_rad,
            'Magnetic field absolute':magnetic_field,                           #at the separatrix
            
            'Outer strike point R':R_outer_strike_point,
            'Outer strike point z':z_outer_strike_point,
            'Lower x point R':R_lower_x_point,
            'Lower x point z':z_lower_x_point,
            
            'Sound speed':c_s,
            'Plasma frequency':omega_pe,
            'Plasma frequency electron':omega_pe,
            'Plasma frequency ion':omega_pi,
            
            'Plasma elongation':elongation,
            'Plasma triangularity upper':upper_triang,
            'Plasma triangularity lower':lower_triang,
            'Plasma triangularity':(upper_triang+lower_triang)/2,
            
            'Minor radius':minor_radius,
            'Magnetic axis radius':R_mag_axis,
            'Pedestal radius':R_separatrix,
            'Larmor radius':rho_e,
            'Larmor radius electron':rho_e,
            'Larmor radius ion':rho_i,
            'Larmor radius sound':rho_s,
            'Larmor frequency electron':omega_gyro_electron,
            'Larmor frequency ion':omega_gyro_ion,
            
            'Inner gap':inner_gap,
            'Outer gap':outer_gap,
            'Current density at 95':cdens_95,
            'Current density at 99':cdens_99,
            
            'Density at max':ne_params['Value at max'][ind],
            'Density pedestal height': ne_params['Height'][ind],
            'Density SOL offset':ne_params['SOL offset'][ind],
            'Density pedestal position':ne_params['Position'][ind],
            'Density pedestal width':ne_params['Width'][ind],
            'Density max gradient':ne_params['Max gradient'][ind],
            'Density SOL':n_e,
            
            'Temperature at max':te_params['Value at max'][ind],
            'Temperature pedestal height': te_params['Height'][ind],
            'Temperature SOL offset':te_params['SOL offset'][ind],
            'Temperature pedestal position':te_params['Position'][ind],
            'Temperature pedestal width':te_params['Width'][ind],
            'Temperature max gradient':te_params['Max gradient'][ind],
            'Temperature SOL':T_e,
            
            'Pressure at max':pe_params['Value at max'][ind],
            'Pressure pedestal height': pe_params['Height'][ind],
            'Pressure SOL offset':pe_params['SOL offset'][ind],
            'Pressure pedestal position':pe_params['Position'][ind],
            'Pressure pedestal width':pe_params['Width'][ind],
            'Pressure max gradient':pe_params['Max gradient'][ind],   
            'Pressure SOL':n_e*T_e,
            
            }

def return_interesting_key_pairs(with_plasma_frequency=False):
    """
    Returns the interesting key paramaters for plotting data for publications.

    Parameters
    ----------
    with_plasma_frequency : boolean, optional
        Return the interesting key pairs including plasma frequency. The default is False.

    Returns
    -------
    interesting_key_pairs : array
        Returns an array with interesting key pairs for plotting. One can set whether the key pairs with plasma frequency are returned.
    units :                 dictionary
        Returns the axis labels for the interesting key pairs as [label, unit, multiplier for data to get it into "unit" units].

    """
    
    if not with_plasma_frequency:
        interesting_key_pairs=np.asarray([['Axes length minor','Line integrated density'], #
                                          ['Angle of least inertia','Line integrated density'],
                                          ['Angle of least inertia','Sound speed'],
                                          #['Angle of least inertia','Plasma frequency'],
                                          ['Angle of least inertia','Pressure at max'],
                                          ['Velocity poloidal centroid','Temperature pedestal width'],
                                          ['Velocity poloidal centroid','Collisionality'],
                                          #['Velocity poloidal centroid','Plasma frequency'],
                                          ['Velocity poloidal centroid','Density at max'],
                                          
                                          ['Angular velocity ALI','Line integrated density'],
                                          ['Angular velocity ALI','Collisionality'],
                                          
                                          #['Angular velocity ALI','Plasma frequency'],
                                          ])
    else:
        interesting_key_pairs=np.asarray([['Axes length minor','Line integrated density'], #
                                          ['Angle of least inertia','Line integrated density'],
                                          ['Angle of least inertia','Sound speed'],
                                          ['Angle of least inertia','Plasma frequency'],
                                          ['Angle of least inertia','Pressure at max'],
                                          ['Velocity poloidal centroid','Temperature pedestal width'],
                                          ['Velocity poloidal centroid','Collisionality'],
                                          ['Velocity poloidal centroid','Plasma frequency'],
                                          ['Velocity poloidal centroid','Density at max'],
                                          
                                          ['Angular velocity ALI','Line integrated density'],
                                          ['Angular velocity ALI','Collisionality'],
                                          
                                          ['Angular velocity ALI','Plasma frequency'],
                                          ])
    
    #Name, unit, multiplier
    units={'Axes length minor':['$b_{ellipse}$','mm', 1e3],
           'Angle of least inertia':['$\\theta_{blob}$','rad', 1],
           'Angular velocity ALI':['$\omega_{blob}$','krad/s',1e-3],
           'Velocity poloidal centroid':['$v_{pol}$','km/s', 1e-3],
           'Line integrated density':['$n_{e,LID}$','$10^{19}\\ m^{-3}$',1e-19],
           'Pressure at max':['$p_{e,max\,\\nabla p}$','kPa',1],
           'Density at max':['$n_{e, max\,\\nabla p}$','$10^{19}\\ m^{-3}$', 1e-19],
           'Temperature pedestal width':['$\\Delta_{T_e,ped}$','mm',1e3],
           'Sound speed':['$c_{s,max\,\\nabla p}$','km/s', 1e-3],
           'Plasma frequency':['$\omega_{p,e,max\,\\nabla p}$','GHz', 1e-9],
           'Collisionality':['$\\nu_{ei,max\,\\nabla p}$','-',1],
           'Connection length':['$\\L_{||}$','m',1],
           'Collisionality dimensionless':['$\\Lambda$','-',1],
           }
    
    return (interesting_key_pairs,units)

def read_blob_elm_database(time_range_around_peak=5e-3,
                           blob_db_file='/Users/mlampert/work/NSTX_workspace/db/2010.csv',
                           elm_db_file='/Users/mlampert/work/NSTX_workspace/db/ELM_findings_mlampert_velocity_good_ne.csv',
                           nofilter=False
                           ):
    """
    Obsolete.

    Parameters
    ----------
    time_range_around_peak : TYPE, optional
        DESCRIPTION. The default is 5e-3.
    blob_db_file : TYPE, optional
        DESCRIPTION. The default is '/Users/mlampert/work/NSTX_workspace/db/2010.csv'.
    elm_db_file : TYPE, optional
        DESCRIPTION. The default is '/Users/mlampert/work/NSTX_workspace/db/ELM_findings_mlampert_velocity_good_ne.csv'.
    nofilter : TYPE, optional
        DESCRIPTION. The default is False.

    Returns
    -------
    database : TYPE
        DESCRIPTION.

    """

    database=np.asarray(pandas.read_csv(blob_db_file))
    ind_shots=np.where(database[:,2]==0)
    blob_shots=database[ind_shots,0][0,:]
    peak_times=database[ind_shots,1][0,:]/1000.
    blob_database={'shot':blob_shots,
                   'time':peak_times}

    db=pandas.read_csv(elm_db_file, index_col=0)
    elm_shots=np.asarray(db)[:,1]
    elm_times=np.asarray(db)[:,3]
    elm_database={'shot':elm_shots,
                  'time':elm_times}
    database={}
    for key in ['shot','time']:
        database[key]=np.append(blob_database[key],elm_database[key])

    return database
